const SOURCE_EVENTS = [
  {
    id: 1,
    title: "Eruption of Mount Vesuvius",
    year: 79,
    clue: "Ash and pyroclastic surges buried Pompeii and Herculaneum beneath Vesuvius.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Destruction_of_Pompeii_and_Herculaneum.jpg/1920px-Destruction_of_Pompeii_and_Herculaneum.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Destruction_of_Pompeii_and_Herculaneum.jpg",
    attribution: "John Martin; Public domain; Wikimedia Commons",
  },
  {
    id: 2,
    title: "Battle of the Milvian Bridge",
    year: 312,
    clue: "Constantine defeated Maxentius beside a bridge over the Tiber.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Battle_of_the_Milvian_Bridge_by_Giulio_Romano%2C_1520-24.jpg/1920px-Battle_of_the_Milvian_Bridge_by_Giulio_Romano%2C_1520-24.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Battle_of_the_Milvian_Bridge_by_Giulio_Romano,_1520-24.jpg",
    attribution: "Giulio Romano; Public domain; Wikimedia Commons",
  },
  {
    id: 3,
    title: "Battle of Hastings",
    year: 1066,
    clue: "Norman forces defeated Harold Godwinson in a decisive fight for England.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Bayeux_Tapestry_scene57_Harold_death.jpg/1920px-Bayeux_Tapestry_scene57_Harold_death.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Bayeux_Tapestry_scene57_Harold_death.jpg",
    attribution: "Bayeux Tapestry, photographed by Myrabella; Public domain; Wikimedia Commons",
  },
  {
    id: 4,
    title: "Magna Carta sealed",
    year: 1215,
    clue: "King John sealed a charter limiting royal power at Runnymede.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg/1920px-Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Magna_Carta_(British_Library_Cotton_MS_Augustus_II.106).jpg",
    attribution: "King John and the barons of England; Public domain; Wikimedia Commons",
  },
  {
    id: 5,
    title: "Fall of Constantinople",
    year: 1453,
    clue: "Ottoman troops captured the Byzantine capital after a long siege.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Siege_of_Constantinople_fresco%2C_Moldovi%C8%9Ba_monastery%2C_Vatra_Moldovi%C8%9Bei%2C_2017.jpg/1920px-Siege_of_Constantinople_fresco%2C_Moldovi%C8%9Ba_monastery%2C_Vatra_Moldovi%C8%9Bei%2C_2017.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Siege_of_Constantinople_fresco,_Moldovi%C8%9Ba_monastery,_Vatra_Moldovi%C8%9Bei,_2017.jpg",
    attribution: "DimiTalen; CC0; Wikimedia Commons",
  },
  {
    id: 6,
    title: "Columbus reaches the Americas",
    year: 1492,
    clue: "Three ships crossed the Atlantic and made landfall in the Caribbean.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Landing_of_Columbus_%282%29_%28cropped%29.jpg/1920px-Landing_of_Columbus_%282%29_%28cropped%29.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Landing_of_Columbus_(2)_(cropped).jpg",
    attribution: "John Vanderlyn; Public domain; Wikimedia Commons",
  },
  {
    id: 7,
    title: "Luther's Ninety-Five Theses",
    year: 1517,
    clue: "Martin Luther's challenge to Church practices ignited the Reformation.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Luther_95_Thesen.png/1920px-Luther_95_Thesen.png",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Luther_95_Thesen.png",
    attribution: "Martin Luther; Public domain; Wikimedia Commons",
  },
  {
    id: 8,
    title: "Fall of Tenochtitlan",
    year: 1521,
    clue: "Spanish-led forces captured the Aztec capital after a brutal siege.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Conquista-de-M%C3%A9xico-por-Cort%C3%A9s-Tenochtitlan-Painting.png/1920px-Conquista-de-M%C3%A9xico-por-Cort%C3%A9s-Tenochtitlan-Painting.png",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Conquista-de-M%C3%A9xico-por-Cort%C3%A9s-Tenochtitlan-Painting.png",
    attribution: "Unknown artist; Public domain; Wikimedia Commons",
  },
  {
    id: 9,
    title: "Defeat of the Spanish Armada",
    year: 1588,
    clue: "English ships and fireships helped scatter Spain's invasion fleet.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Spanish_Armada_fireships.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Spanish_Armada_fireships.jpg",
    attribution: "Unknown artist; Public domain; Wikimedia Commons",
  },
  {
    id: 10,
    title: "Mayflower reaches Plymouth",
    year: 1620,
    clue: "Pilgrims crossed the Atlantic and established Plymouth Colony.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Copyrighted_and_Published_by_A_S_Burbank%2C_The_Mayflower_at_Sea_%28NBY_21340%29.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Copyrighted_and_Published_by_A_S_Burbank,_The_Mayflower_at_Sea_(NBY_21340).jpg",
    attribution: "Unknown artist; Public domain; Wikimedia Commons",
  },
  {
    id: 11,
    title: "Great Fire of London",
    year: 1666,
    clue: "A bakery fire grew into an inferno that devastated the English capital.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Great_Fire_London.jpg/1920px-Great_Fire_London.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Great_Fire_London.jpg",
    attribution: "Unknown artist; Public domain; Wikimedia Commons",
  },
  {
    id: 12,
    title: "Declaration of American Independence",
    year: 1776,
    clue: "Thirteen colonies formally announced their separation from Britain.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/United_States_Declaration_of_Independence.jpg/1920px-United_States_Declaration_of_Independence.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:United_States_Declaration_of_Independence.jpg",
    attribution: "Second Continental Congress; reproduction by William Stone; Public domain; Wikimedia Commons",
  },
  {
    id: 13,
    title: "Storming of the Bastille",
    year: 1789,
    clue: "A Paris crowd seized the fortress-prison that symbolized royal authority.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Anonymous_-_Prise_de_la_Bastille.jpg/1920px-Anonymous_-_Prise_de_la_Bastille.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Anonymous_-_Prise_de_la_Bastille.jpg",
    attribution: "Unidentified painter; Public domain; Wikimedia Commons",
  },
  {
    id: 14,
    title: "Haitian Revolution begins",
    year: 1791,
    clue: "Enslaved people in Saint-Domingue rose up against French colonial rule.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/44/Incendie_de_la_Plaine_du_Cap._Massacre_des_Blancs_par_les_esclaves_noirs_r%C3%A9volt%C3%A9s._France_militaire._Martinet_et_Masson.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Incendie_de_la_Plaine_du_Cap._Massacre_des_Blancs_par_les_esclaves_noirs_r%C3%A9volt%C3%A9s._France_militaire._Martinet_et_Masson.jpg",
    attribution: "Aaron Martinet and Alphonse-Charles Masson; Public domain; Wikimedia Commons",
  },
  {
    id: 15,
    title: "Coronation of Napoleon",
    year: 1804,
    clue: "Napoleon crowned himself emperor inside Notre-Dame Cathedral.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Jacques-Louis_David_-_The_Coronation_of_Napoleon_%281805-1807%29.jpg/1920px-Jacques-Louis_David_-_The_Coronation_of_Napoleon_%281805-1807%29.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Jacques-Louis_David_-_The_Coronation_of_Napoleon_(1805-1807).jpg",
    attribution: "Jacques-Louis David and Georges Rouget; Public domain; Wikimedia Commons",
  },
  {
    id: 16,
    title: "Mexican War of Independence begins",
    year: 1810,
    clue: "A priest's call to arms began Mexico's struggle against Spanish rule.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/96/Collage_Independencia.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Collage_Independencia.jpg",
    attribution: "Hpav7; Public domain; Wikimedia Commons",
  },
  {
    id: 17,
    title: "Battle of Waterloo",
    year: 1815,
    clue: "Napoleon suffered his final defeat against a coalition army in Belgium.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Battle_of_Waterloo_1815.PNG",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Battle_of_Waterloo_1815.PNG",
    attribution: "William Sadler; Public domain; Wikimedia Commons",
  },
  {
    id: 18,
    title: "Independence of Brazil",
    year: 1822,
    clue: "Pedro declared the country's break from Portugal beside the Ipiranga.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Pedro_Am%C3%A9rico_-_Independ%C3%AAncia_ou_Morte_-_Google_Art_Project.jpg/1920px-Pedro_Am%C3%A9rico_-_Independ%C3%AAncia_ou_Morte_-_Google_Art_Project.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Pedro_Am%C3%A9rico_-_Independ%C3%AAncia_ou_Morte_-_Google_Art_Project.jpg",
    attribution: "Pedro Américo; Public domain; Wikimedia Commons",
  },
  {
    id: 19,
    title: "California Gold Rush begins",
    year: 1848,
    clue: "A discovery at Sutter's Mill drew fortune seekers from around the world.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/1850_Woman_and_Men_in_California_Gold_Rush.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:1850_Woman_and_Men_in_California_Gold_Rush.jpg",
    attribution: "Unknown photographer; Public domain; Wikimedia Commons",
  },
  {
    id: 20,
    title: "The Great Exhibition opens",
    year: 1851,
    clue: "A vast glass palace hosted an international showcase of industry and design.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/The_Crystal_Palace_in_Hyde_Park_for_Grand_International_Exhibition_of_1851.jpg/1920px-The_Crystal_Palace_in_Hyde_Park_for_Grand_International_Exhibition_of_1851.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:The_Crystal_Palace_in_Hyde_Park_for_Grand_International_Exhibition_of_1851.jpg",
    attribution: "Read & Co.; Public domain; Wikimedia Commons",
  },
  {
    id: 21,
    title: "Indian Rebellion begins",
    year: 1857,
    clue: "Soldiers and civilians rose against East India Company rule.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Indian_Rebellion_of_1857.jpg/1920px-Indian_Rebellion_of_1857.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Indian_Rebellion_of_1857.jpg",
    attribution: "Unknown artist; Public domain; Wikimedia Commons",
  },
  {
    id: 22,
    title: "Attack on Fort Sumter",
    year: 1861,
    clue: "Confederate artillery fired on a federal fort in Charleston Harbor.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Bombardment_of_Fort_Sumter.jpg/1920px-Bombardment_of_Fort_Sumter.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Bombardment_of_Fort_Sumter.jpg",
    attribution: "Currier & Ives; Public domain; Wikimedia Commons",
  },
  {
    id: 23,
    title: "Meiji Restoration",
    year: 1868,
    clue: "Imperial rule returned as Japan began rapid political and industrial change.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/de/Emperor_Meiji_by_Takahashi_Yuichi.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Emperor_Meiji_by_Takahashi_Yuichi.jpg",
    attribution: "Takahashi Yuichi; Public domain; Wikimedia Commons",
  },
  {
    id: 24,
    title: "First modern Olympic Games",
    year: 1896,
    clue: "The first international revival of the ancient Games was held in Athens.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/BASA-3K-7-422-21-1896_Summer_Olympics.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:BASA-3K-7-422-21-1896_Summer_Olympics.jpg",
    attribution: "Unknown photographer; Public domain; Wikimedia Commons",
  },
  {
    id: 25,
    title: "Federation of Australia",
    year: 1901,
    clue: "Six colonies united as a single Commonwealth.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Town_Hall%2C_Sydney%2C_Inauguration_of_Australian_Commonwealth.jpg/1920px-Town_Hall%2C_Sydney%2C_Inauguration_of_Australian_Commonwealth.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Town_Hall,_Sydney,_Inauguration_of_Australian_Commonwealth.jpg",
    attribution: "W. A. Gullick; Public domain; Wikimedia Commons",
  },
  {
    id: 26,
    title: "Wright brothers' first flight",
    year: 1903,
    clue: "A powered aircraft lifted off at Kitty Hawk.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/First_flight2.jpg/1920px-First_flight2.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:First_flight2.jpg",
    attribution: "John T. Daniels; Public domain; Wikimedia Commons",
  },
  {
    id: 27,
    title: "San Francisco earthquake",
    year: 1906,
    clue: "A massive quake and fires devastated San Francisco.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Post-and-Grant-Avenue-Look.jpg/1920px-Post-and-Grant-Avenue-Look.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Post-and-Grant-Avenue-Look.jpg",
    attribution: "H. D. Chadwick; Public domain; Wikimedia Commons",
  },
  {
    id: 28,
    title: "Sinking of the Titanic",
    year: 1912,
    clue: "The ocean liner struck an iceberg and sank on its maiden voyage.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/St%C3%B6wer_Titanic.jpg/1920px-St%C3%B6wer_Titanic.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:St%C3%B6wer_Titanic.jpg",
    attribution: "Willy Stöwer; Public domain; Wikimedia Commons",
  },
  {
    id: 29,
    title: "Assassination of Archduke Franz Ferdinand",
    year: 1914,
    clue: "A gunman killed the heir to the Austro-Hungarian throne in Sarajevo.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ea/DC-1914-27-d-Sarajevo-cropped.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:DC-1914-27-d-Sarajevo-cropped.jpg",
    attribution: "Achille Beltrame; Public domain; Wikimedia Commons",
  },
  {
    id: 30,
    title: "October Revolution",
    year: 1917,
    clue: "Bolsheviks seized key sites and overthrew the provisional government.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b4/After_the_capture_of_the_Winter_Palace_26_October_1917.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:After_the_capture_of_the_Winter_Palace_26_October_1917.jpg",
    attribution: "Pyotr Novitsky; Public domain; Wikimedia Commons",
  },
  {
    id: 31,
    title: "Discovery of Tutankhamun's tomb",
    year: 1922,
    clue: "Howard Carter's team uncovered a pharaoh's nearly intact tomb in the Valley of the Kings.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/The_Moment_Carter_Opens_the_Shrine.jpg/1920px-The_Moment_Carter_Opens_the_Shrine.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:The_Moment_Carter_Opens_the_Shrine.jpg",
    attribution: "Harry Burton; Public domain; Wikimedia Commons",
  },
  {
    id: 32,
    title: "Salt March",
    year: 1930,
    clue: "Gandhi led a march to the sea in protest of British salt laws.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Marche_sel.jpg/1920px-Marche_sel.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Marche_sel.jpg",
    attribution: "Unknown photographer; Public domain; Wikimedia Commons",
  },
  {
    id: 33,
    title: "Hindenburg disaster",
    year: 1937,
    clue: "A giant passenger airship burst into flames while docking in New Jersey.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Hindenburg_disaster.jpg/1920px-Hindenburg_disaster.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Hindenburg_disaster.jpg",
    attribution: "Sam Shere; Public domain; Wikimedia Commons",
  },
  {
    id: 34,
    title: "Invasion of Poland",
    year: 1939,
    clue: "German forces crossed the border, beginning the European war.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/07/Bundesarchiv_Bild_183-H27915%2C_Danzig%2C_Enfernen_eines_polnischen_Hoheitszeichens.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Bundesarchiv_Bild_183-H27915,_Danzig,_Enfernen_eines_polnischen_Hoheitszeichens.jpg",
    attribution: "Hans Sönnke, Bundesarchiv; CC BY-SA 3.0 DE; Wikimedia Commons",
  },
  {
    id: 35,
    title: "Attack on Pearl Harbor",
    year: 1941,
    clue: "Japanese aircraft launched a surprise attack on the U.S. Pacific Fleet.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Attack_on_Pearl_Harbor_Japanese_planes_view.jpg/1920px-Attack_on_Pearl_Harbor_Japanese_planes_view.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Attack_on_Pearl_Harbor_Japanese_planes_view.jpg",
    attribution: "Imperial Japanese Navy; Public domain; Wikimedia Commons",
  },
  {
    id: 36,
    title: "Normandy landings",
    year: 1944,
    clue: "Allied troops stormed beaches in Normandy during the liberation of Western Europe.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Into_the_Jaws_of_Death_23-0455M_edit.jpg/1920px-Into_the_Jaws_of_Death_23-0455M_edit.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Into_the_Jaws_of_Death_23-0455M_edit.jpg",
    attribution: "Robert F. Sargent, U.S. Coast Guard; Public domain; Wikimedia Commons",
  },
  {
    id: 37,
    title: "Atomic bombing of Hiroshima",
    year: 1945,
    clue: "An atomic bomb destroyed much of Hiroshima near the end of the war.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Atomic_bombing_of_Japan.jpg/1920px-Atomic_bombing_of_Japan.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Atomic_bombing_of_Japan.jpg",
    attribution: "George R. Caron and Charles Levy; Public domain; Wikimedia Commons",
  },
  {
    id: 38,
    title: "Partition of India",
    year: 1947,
    clue: "The end of British rule split the subcontinent and displaced millions.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/A_refugee_special_train_at_Ambala_Station_during_partition_of_India.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:A_refugee_special_train_at_Ambala_Station_during_partition_of_India.jpg",
    attribution: "Photo Division, Government of India; Public domain; Wikimedia Commons",
  },
  {
    id: 39,
    title: "Proclamation of the People's Republic of China",
    year: 1949,
    clue: "Mao Zedong proclaimed a new state from Tiananmen Gate.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/85/Mao_Proclaiming_New_China.JPG",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Mao_Proclaiming_New_China.JPG",
    attribution: "Orihara1; Public domain; Wikimedia Commons",
  },
  {
    id: 40,
    title: "First confirmed ascent of Mount Everest",
    year: 1953,
    clue: "Edmund Hillary and Tenzing Norgay completed the first confirmed ascent.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Edmund_Hillary_and_Tenzing_Norgay.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Edmund_Hillary_and_Tenzing_Norgay.jpg",
    attribution: "Jamling Tenzing Norgay; CC BY-SA 3.0; Wikimedia Commons",
  },
  {
    id: 41,
    title: "Launch of Sputnik",
    year: 1957,
    clue: "The Soviet Union placed the first artificial satellite into orbit.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D0%B2_%D0%BC%D0%B8%D1%80%D0%B5_%D0%B8%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA_%D0%97%D0%B5%D0%BC%D0%BB%D0%B8.jpg/1920px-%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D0%B2_%D0%BC%D0%B8%D1%80%D0%B5_%D0%B8%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA_%D0%97%D0%B5%D0%BC%D0%BB%D0%B8.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D0%B2_%D0%BC%D0%B8%D1%80%D0%B5_%D0%B8%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA_%D0%97%D0%B5%D0%BC%D0%BB%D0%B8.jpg",
    attribution: "Andrey Butko; CC BY-SA 3.0; Wikimedia Commons",
  },
  {
    id: 42,
    title: "March on Washington",
    year: 1963,
    clue: "Hundreds of thousands gathered in Washington for civil rights and jobs.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Civil_rights_march_on_Washington%2C_D.C._from_Lincoln_%28cropped%29.jpg/1920px-Civil_rights_march_on_Washington%2C_D.C._from_Lincoln_%28cropped%29.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Civil_rights_march_on_Washington,_D.C._from_Lincoln_(cropped).jpg",
    attribution: "Rowland Scherman; Public domain; Wikimedia Commons",
  },
  {
    id: 43,
    title: "Apollo 11 Moon landing",
    year: 1969,
    clue: "Humans walked on the Moon for the first time.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/A_Man_on_the_Moon%2C_AS11-40-5903_%28cropped%29.jpg/1920px-A_Man_on_the_Moon%2C_AS11-40-5903_%28cropped%29.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:A_Man_on_the_Moon,_AS11-40-5903_(cropped).jpg",
    attribution: "Neil A. Armstrong, NASA; Public domain; Wikimedia Commons",
  },
  {
    id: 44,
    title: "Fall of Saigon",
    year: 1975,
    clue: "Helicopters evacuated people as North Vietnamese forces captured the capital.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Helicopter_evacuation_of_Saigon_atop_22_Gia_Long_Street.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Helicopter_evacuation_of_Saigon_atop_22_Gia_Long_Street.webp",
    attribution: "Hubert van Es; Public domain; Wikimedia Commons",
  },
  {
    id: 45,
    title: "Fall of the Berlin Wall",
    year: 1989,
    clue: "Crowds crossed and chipped apart the barrier dividing East and West Berlin.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1c/West_and_East_Germans_at_the_Brandenburg_Gate_in_1989.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:West_and_East_Germans_at_the_Brandenburg_Gate_in_1989.jpg",
    attribution: "Unknown photographer, reproduction by Lear 21; CC BY-SA 3.0; Wikimedia Commons",
  },
  {
    id: 46,
    title: "South Africa's first multiracial election",
    year: 1994,
    clue: "Citizens of every race voted together in the country's first universal-suffrage election.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/73/Mandela_voting_in_1994.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Mandela_voting_in_1994.jpg",
    attribution: "Paul Weinberg; CC BY-SA 3.0; Wikimedia Commons",
  },
  {
    id: 47,
    title: "Handover of Hong Kong",
    year: 1997,
    clue: "British rule ended and the territory returned to Chinese sovereignty.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Image_shows_the_Union_and_Chinese_Flags_together._MOD_45157410.jpg/1920px-Image_shows_the_Union_and_Chinese_Flags_together._MOD_45157410.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Image_shows_the_Union_and_Chinese_Flags_together._MOD_45157410.jpg",
    attribution: "Sergeant Paul Shaw LBIPP; Open Government Licence v1.0; Wikimedia Commons",
  },
  {
    id: 48,
    title: "September 11 attacks",
    year: 2001,
    clue: "Hijacked airliners struck the World Trade Center and the Pentagon.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/35/WTC_smoking_on_9-11.jpeg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:WTC_smoking_on_9-11.jpeg",
    attribution: "Michael Foran; CC BY 2.0; Wikimedia Commons",
  },
  {
    id: 49,
    title: "Egyptian Revolution",
    year: 2011,
    clue: "Mass protests centered on Tahrir Square forced a longtime president from power.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Tahrir_Square_during_8_February_2011.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Tahrir_Square_during_8_February_2011.jpg",
    attribution: "Mona; CC BY 2.0; Wikimedia Commons",
  },
  {
    id: 50,
    title: "COVID-19 becomes a global pandemic",
    year: 2020,
    clue: "A novel coronavirus outbreak became a worldwide public-health crisis.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Covid-19_SP_-_UTI_V._Nova_Cachoeirinha.jpg/1920px-Covid-19_SP_-_UTI_V._Nova_Cachoeirinha.jpg",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Covid-19_SP_-_UTI_V._Nova_Cachoeirinha.jpg",
    attribution: "Gustavo Basso; CC BY-SA 4.0; Wikimedia Commons",
  },
];

export const HISTORICAL_EVENTS = SOURCE_EVENTS.map(
  ({ imageUrl: sourceImageUrl, ...historicalEvent }) => ({
    ...historicalEvent,
    imageUrl: `/when-was-it/events/${String(historicalEvent.id).padStart(
      3,
      "0",
    )}.webp`,
    sourceImageUrl,
  }),
);
