name: GH Pages Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"

  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  build-deploy:
    name: Build and deploy app

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install 🔧
        run: npm install
        env:
          CI: ""

      - name: Build 🏗️
        run: npm run build

      - name: Deploy to GH Pages 🚀
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
